# Generated by Django 3.2.7 on 2021-10-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='marks',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='graded',
            field=models.BooleanField(default=True),
        ),
    ]
