# Generated by Django 3.2.7 on 2021-09-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='problem_statement',
            field=models.FileField(default=None, upload_to='assignments/'),
        ),
    ]
