# Generated by Django 3.2.7 on 2021-09-28 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_assignment_problem_statement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='deadline',
        ),
    ]
