# Generated by Django 3.2.7 on 2021-10-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211018_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='marks',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='graded',
            field=models.BooleanField(default=False),
        ),
    ]
