# Generated by Django 3.2.7 on 2021-11-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_assignment_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='weightage',
            field=models.IntegerField(default=0),
        ),
    ]
