# Generated by Django 3.2.7 on 2021-10-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_assignment_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roll_number',
            field=models.IntegerField(unique=True),
        ),
    ]
