# Generated by Django 3.2.7 on 2021-10-08 15:33

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='problem_statement',
            field=models.FileField(default=None, upload_to=users.models.upload_path),
        ),
    ]
